config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :games, only: [:index, :show] do
    post :start, on: :collection
    member do
      post :hit
      post :stand
    end
  end

end

app/models/card_stack.rb
class CardStack < ActiveRecord::Base
  belongs_to :game

  serialize :value, Hash

  DECK_COUNT = 6
  SPECIAL_CARDS = { a: 11, j: 10, k: 10, q: 10 }
  CARDS = (2..10).to_a + SPECIAL_CARDS.keys
  CARDS_VALUE_HASH = CARDS.inject(Hash.new { |hash, key| hash[key] = 0 }) do |cards_hash, card|
    cards_hash[card.to_s] += 1 * DECK_COUNT * 4
    cards_hash
  end

  def initialize(*args)
    super
    self.value = CARDS_VALUE_HASH
  end

  def find_card
    found = CARDS.sample
    if can_give_card?(found)
      found
    else
      find_a_card
    end
  end

  def self.find_card_value(card)
    SPECIAL_CARDS.fetch(card, card)
  end

  def updated_value(card)
    value[card.to_s] -= 1
    value
  end

  private

  def can_give_card?(card)
    value[card.to_s] > 0
  end
end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :player
  has_many :steps
  has_one :card_stack

  validates :player, presence: true

  scope :with_status, ->(status) { where(won: status) }
  scope :not_tie, -> { where.not("player_score = dealer_score") }
  scope :lost, -> { not_tie.with_status(false) }
  scope :won, -> { not_tie.with_status(true) }
  scope :busted, -> { lost.where("player_score > ?", 21) }
  scope :lost_without_bust, -> { lost.where(player_score: (17...21)) }

  def self.day_stats
    Game.select("DATE(created_at) date, SUM(IF(won=0, bet, 0)) revenue, (SUM(IF(won=0, bet, 0)) - SUM(IF(won=1, bet, 0))) profit")
        .group("date(created_at)")
  end

  def start
    #give 2 cards to player, give 1 card to dealer
    initialize_stack
    give_cards(2)
    give_cards(1, false)
    analyze_scores
  end

  def over?
    !self.won.nil? || tie?
  end

  def tie?
    player_score == dealer_score
  end

  def hit
    give_cards(1)
    analyze_scores
  end

  def stand
    give_cards(1, false)
    analyze_scores(false)
  end

  private

  def initialize_stack
    build_card_stack
  end

  def give_cards(number_of_cards, player = true)
    #find a card, make a note of card found, change score of the card/dealer
    number_of_cards.times do |card|
      found_card = card_stack.find_card
      card_stack.value = card_stack.updated_value(found_card)
      steps.build(for_player: player, card: found_card)
      change_score(player, found_card)
    end
  end

  def change_score(player, card)
    card_value = CardStack.find_card_value(card)
    if player
      self.player_score += card_value
    else
      self.dealer_score += card_value
    end
  end

  def analyze_scores(player = true)
    if black_jack?(player)
      self.won = player
    elsif bust?(player)
      self.won = !player
    elsif !player
      if dealer_score <= 16
        stand
      else
        self.won = compare_scores_and_declare_winner
      end
    end
    save
  end

  def bust?(player)
    desired_player_score(player) > 21
  end

  def black_jack?(player)
    desired_player_score(player) == 21
  end

  def desired_player_score(player)
    player ? player_score : dealer_score
  end

  def compare_scores_and_declare_winner
    player_score > dealer_score
  end
end

app/models/player.rb
class Player < ActiveRecord::Base
  has_many :games
  has_many :steps, through: :games

  def average_score
    games.won.average(:player_score)
  end

  def lucky_cards
    steps.for_player(true).select("card, count(*) frequency").group(:card).order("count(*) desc")
  end
end

app/models/step.rb
class Step < ActiveRecord::Base
  belongs_to :game

  validates :game, :card, presence: true
  validates :card, inclusion: { in: CardStack::CARDS.map(&:to_s) } , allow_blank: true

  scope :for_player, ->(player) { where(for_player: player ) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_player_session, only: :start
  before_action :load_player, only: [:index, :show, :hit, :stand]
  before_action :load_game, only: [:show, :hit, :stand]
  before_action :check_game_over, only: [:hit, :stand]

  def index
    @games = @player.games
    @busted_games = @games.busted
    @lost_without_bust_games = @games.lost_without_bust
    @games = @games.to_a
  end

  def show
  end

  def start
    @game = @player.games.new
    if @game.start
      redirect_to game_path(@game)
    else
      redirect_to root_path, alert: @game.errors.full_messages.to_sentence
    end
  end

  def hit
    unless @game.hit
      flash[:error] = @game.errors.full_messages.to_sentence 
    end
    redirect_to game_path(@game)
  end

  def stand
    unless @game.stand
      flash[:error] = @game.errors.full_messages.to_sentence 
    end
    redirect_to game_path(@game)
  end

  private

    def load_game
      unless @game = Game.where(id: params[:id]).first
        redirect_to root_path, alert: 'Game not found'
      end
    end

    def set_player_session
      unless @player = Player.where(id: session[:player_id]).first
        @player = Player.create 
        session[:player_id] = @player.id
      end
    end

    def load_player
      unless @player = Player.where(id: session[:player_id]).first
        redirect_to root_path, alert: 'Player not found'
      end
    end

    def check_game_over
      if @game.over?
        redirect_to game_path(@game)
      end
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :clear_user_session

  def index
  end

  private

  def clear_user_session
    session[:player_id] = nil
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_flash(flash=[])
    flash_view = "<div class='flash' id='flash'>"
    flash.collect do |type, message|
        flash_view += "<div class ='message #{ type }'>"
        flash_view += "<p> #{message} </p>"
        flash_view += "</div>"
    end
    flash_view +='</div>'
    flash_view.html_safe
  end
end

app/helpers/games_helper.rb
module GamesHelper
  def winner_text(game)
    return "It's a tie" if game.tie?
    "#{ game.won? ? 'Player' : 'Dealer' } Wins"
  end

  def steps_for(game, player)
    game.steps.for_player(player)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/games/_game_steps.html.erb
<div>
  <% steps_for(game, player).each do |step| %>
    <div class='cards inline-block'>
      <%= step.card.capitalize %>
    </div>
  <% end %>
</div>

app/views/games/_play_more.html.erb
<div class="inline-block game-steps">
  DEALER
  <%= render partial: 'game_steps', locals: { player: false, game: game }  %>
</div>
<div class="inline-block game-steps">
  PLAYER
  <%= render partial: 'game_steps', locals: { player: true, game: game }  %>
  <div>
    <%= button_to 'Pick a card', hit_game_path(game) %>
    <%= button_to 'Skip', stand_game_path(game) %>
  </div>
</div>

app/views/games/_winner_page.html.erb
<div>
  <%= winner_text(game) %>
</div>

<div>
  <%= link_to 'Deal Again', start_games_path, method: :post %>
  <%= link_to 'Show Statistics', games_path %>
</div>

app/views/games/index.html.erb
<h1>Casino Daily Statistics</h1>
<div class='inline-block game-stats'>
  <div>Date</div>
  <div>Revenue</div>
  <div>Profit</div>
</div>

<% Game.day_stats.each do |day| %>
  <div class='inline-block game-stats'>
    <div><%= day.date %></div>
    <div><%= day.revenue %></div>
    <div><%= day.profit %></div>
  </div>
<% end %>


<h1>Player Statistics</h1>
<div class='inline-block game-stats'>
  <div></div>
  <div>Dealer</div>
  <div>Player</div>
</div>

<% @games.each_with_index do |game, index| %>
  <div class='inline-block game-stats'>
    <div><%= "GAME#{ index + 1 }" %></div>
    <div><%= game.dealer_score %></div>
    <div><%= game.player_score %></div>
  </div>
<% end %>

<h3>Score Analysis</h3>
<div>
  <div>Games Lost with score 21+ : <%= @busted_games.count %></div>
  <div>Games Lost with score 17+ : <%= @lost_without_bust_games.count %></div>
  <div>Average Score: <%= @player.average_score %></div>
</div>

<h3>Lucky Cards</h3>
<div class='inline-block game-stats'>
  <div>Card</div>
  <div>Frequency</div>
</div>

<% @player.lucky_cards.each do |card_frequency_pair| %>
  <div class='inline-block game-stats'>
    <div><%= card_frequency_pair.card.capitalize %></div>
    <div><%= card_frequency_pair.frequency %></div>
  </div>
<% end %>

<div>
  <%= button_to 'Deal Again', start_games_path %>
</div>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<% if @game.over? %>
  <%= render partial: 'winner_page', locals: { game: @game } %>
<% else %>
  <%= render partial: 'play_more', locals: { game: @game }%>
<% end %>

app/views/home/index.html.erb
Welcome Player
<%= button_to 'Start Game', start_games_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blackjack</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render_flash %>
<%= yield %>

</body>
</html>